allowBuilds:
  '@webos-tools/cli@https://codeload.github.com/fire332/webos-cli/tar.gz/6cfbcf231a0fa1e50519d370ee6e5edc71c4998a': true
  core-js-pure: true
  cpu-features: true
  ssh2: true
onlyBuiltDependencies:
  - '@webos-tools/cli'
  - core-js-pure
  - cpu-features
  - ssh2
